name: "Refresh SSL Cert From Stock Asus DDNS Router"
version: 0.1.2
slug: "refresher_ssl_cert_from_stock_asus_router_ssh_i_option"
image: "ghcr.io/kf042020/refresher-ssl-cert-from-stock-asus-router-{arch}"
description: "An Add-on that help refresh the SSL certificate under the /SSL folder from Stock Asus Router DDNS (-i ssh option version)"
startup: application
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - ssl:rw
  - config
environment:
  CONFIG_PATH: /data/options.json
init: false
apparmor: true
host_network: true
homeassistant_api: true
options:
  sslFromAsusRouter:
    routerUser: null
    routerIp: null
    routerSshPort: 22
    rsaPrivateKeyPath: null
    keyFilePathOnRouter: null
    certFilePathOnRouter: null
    statusHelper: null
schema:
  sslFromAsusRouter:
    routerUser: str
    routerIp: str
    routerSshPort: int
    rsaPrivateKeyPath: str
    keyFilePathOnRouter: str
    certFilePathOnRouter: str
    statusHelper?: str
